/**
 * Conversations Data
 * 
 * Chat sessions with the AI assistant, including conversations
 * where decision automations were created or discussed.
 */

import type { Conversation } from './types';

export const conversations: Conversation[] = [
  {
    id: 'conv-credit-risk-creation',
    title: 'Create Credit Risk Assessment Automation',
    description: 'Initial conversation where the credit risk automation was generated by AI',
    
    type: 'canvas',
    status: 'archived',
    
    messageIds: [
      'msg-cr-001',
      'msg-cr-002',
      'msg-cr-003',
      'msg-cr-004',
      'msg-cr-005',
      'msg-cr-006',
    ],
    
    artifactIds: [
      'artifact-credit-dm',
      'artifact-fraud-ml',
      'artifact-credit-rules',
    ],
    
    // This conversation created the automation!
    contextAutomationId: 'automation-6-24-20',
    
    userId: 'user-dom',
    userName: 'Dom Washburn',
    userEmail: 'domwashburn@us.ibm.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-06-24T14:30:00.000Z',
    lastMessageDate: '2025-06-24T15:45:12.000Z',
    lastUpdatedDate: '2025-06-24T15:45:12.000Z',
    
    messageCount: 6,
    artifactCount: 3,
    totalTokens: 8542,
    
    tags: [
      { id: 'tag-creation', label: 'Creation', color: 'green' },
      { id: 'tag-banking', label: 'Banking', color: 'blue' },
      { id: 'tag-ai-generated', label: 'AI Generated', color: 'purple' },
    ],
    
    isFavorite: true,
    isPinned: true,
    
    isShared: true,
    sharedWith: ['sarah.chen@company.com', 'james.patterson@company.com'],
    
    summary: 'Created comprehensive credit risk assessment automation with fraud detection and multi-factor scoring. Generated 3 decision models with AI assistance.',
  },
  
  {
    id: 'conv-churn-prediction',
    title: 'Build Customer Churn Prediction Model',
    description: 'Designed ML-based churn prediction automation',
    
    type: 'canvas',
    status: 'archived',
    
    messageIds: [
      'msg-churn-001',
      'msg-churn-002',
      'msg-churn-003',
      'msg-churn-004',
    ],
    
    artifactIds: [
      'artifact-churn-ml',
      'artifact-churn-rules',
    ],
    
    contextAutomationId: 'churn-prediction-model',
    
    userId: 'user-sarah',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-08-10T09:00:00.000Z',
    lastMessageDate: '2025-08-10T11:30:00.000Z',
    lastUpdatedDate: '2025-08-10T11:30:00.000Z',
    
    messageCount: 4,
    artifactCount: 2,
    totalTokens: 5234,
    
    tags: [
      { id: 'tag-ml', label: 'Machine Learning', color: 'blue' },
      { id: 'tag-ai-generated', label: 'AI Generated', color: 'purple' },
    ],
    
    isFavorite: true,
    isPinned: false,
    
    isShared: false,
    
    summary: 'Developed churn prediction model using historical customer data and behavioral patterns.',
  },
  
  {
    id: 'conv-dashboard-analytics',
    title: 'Create Analytics Dashboard Automation',
    description: 'Built automated analytics dashboard with real-time metrics',
    
    type: 'canvas',
    status: 'archived',
    
    messageIds: [
      'msg-dash-001',
      'msg-dash-002',
      'msg-dash-003',
    ],
    
    artifactIds: [
      'artifact-dashboard-config',
      'artifact-metrics-def',
    ],
    
    contextAutomationId: 'dashboard-analytics-auto',
    
    userId: 'user-lisa',
    userName: 'Lisa Wang',
    userEmail: 'lisa.wang@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-09-05T13:00:00.000Z',
    lastMessageDate: '2025-09-05T14:20:00.000Z',
    lastUpdatedDate: '2025-09-05T14:20:00.000Z',
    
    messageCount: 3,
    artifactCount: 2,
    totalTokens: 3890,
    
    tags: [
      { id: 'tag-analytics', label: 'Analytics', color: 'cyan' },
      { id: 'tag-ai-generated', label: 'AI Generated', color: 'purple' },
    ],
    
    isFavorite: false,
    isPinned: false,
    
    isShared: true,
    sharedWith: ['michael.rodriguez@company.com'],
    
    summary: 'Created real-time analytics dashboard automation with custom KPIs and visualizations.',
  },
  
  {
    id: 'conv-improve-fraud-detection',
    title: 'Enhance Fraud Detection Model',
    description: 'Discussion on improving existing fraud detection capabilities',
    
    type: 'chat',
    status: 'active',
    
    messageIds: [
      'msg-fraud-001',
      'msg-fraud-002',
      'msg-fraud-003',
      'msg-fraud-004',
      'msg-fraud-005',
    ],
    
    artifactIds: [
      'artifact-fraud-improvements',
    ],
    
    contextServiceId: 'service-fraud-detection',
    contextAutomationId: 'automation-6-24-20',
    
    userId: 'user-james',
    userName: 'James Patterson',
    userEmail: 'james.patterson@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-10-14T10:00:00.000Z',
    lastMessageDate: '2025-10-14T11:45:00.000Z',
    lastUpdatedDate: '2025-10-14T11:45:00.000Z',
    
    messageCount: 5,
    artifactCount: 1,
    totalTokens: 4120,
    
    tags: [
      { id: 'tag-improvement', label: 'Improvement', color: 'orange' },
      { id: 'tag-security', label: 'Security', color: 'red' },
    ],
    
    isFavorite: false,
    isPinned: true,
    
    isShared: false,
  },
  
  {
    id: 'conv-review-credit-model',
    title: 'Review Credit Decision Model',
    description: 'Reviewing and refining the credit scoring model',
    
    type: 'review',
    status: 'active',
    
    messageIds: [
      'msg-review-001',
      'msg-review-002',
      'msg-review-003',
    ],
    
    artifactIds: [],
    
    contextAssetId: 'asset-credit-dm-001',
    contextServiceId: 'service-credit-risk',
    contextAutomationId: 'automation-6-24-20',
    
    userId: 'user-dom',
    userName: 'Dom Washburn',
    userEmail: 'domwashburn@us.ibm.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-10-15T14:00:00.000Z',
    lastMessageDate: '2025-10-15T15:30:00.000Z',
    lastUpdatedDate: '2025-10-15T15:30:00.000Z',
    
    messageCount: 3,
    artifactCount: 0,
    totalTokens: 2340,
    
    tags: [
      { id: 'tag-review', label: 'Review', color: 'yellow' },
    ],
    
    isFavorite: false,
    isPinned: false,
    
    isShared: false,
  },
  
  {
    id: 'conv-brainstorm-customer-seg',
    title: 'Brainstorm Customer Segmentation Strategy',
    description: 'Ideation session for customer segmentation automation',
    
    type: 'brainstorm',
    status: 'active',
    
    messageIds: [
      'msg-brain-001',
      'msg-brain-002',
      'msg-brain-003',
      'msg-brain-004',
      'msg-brain-005',
      'msg-brain-006',
      'msg-brain-007',
    ],
    
    artifactIds: [
      'artifact-seg-strategy',
      'artifact-seg-criteria',
    ],
    
    contextAutomationId: 'customer-segmentation-ai',
    
    userId: 'user-sarah',
    userName: 'Sarah Chen',
    userEmail: 'sarah.chen@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-10-10T09:00:00.000Z',
    lastMessageDate: '2025-10-10T12:30:00.000Z',
    lastUpdatedDate: '2025-10-10T12:30:00.000Z',
    
    messageCount: 7,
    artifactCount: 2,
    totalTokens: 6780,
    
    tags: [
      { id: 'tag-brainstorm', label: 'Brainstorming', color: 'pink' },
      { id: 'tag-strategy', label: 'Strategy', color: 'blue' },
    ],
    
    isFavorite: true,
    isPinned: false,
    
    isShared: true,
    sharedWith: ['lisa.wang@company.com'],
  },
  
  {
    id: 'conv-debug-loan-approval',
    title: 'Debug Loan Approval Automation',
    description: 'Troubleshooting edge cases in loan approval logic',
    
    type: 'debug',
    status: 'active',
    
    messageIds: [
      'msg-debug-001',
      'msg-debug-002',
      'msg-debug-003',
      'msg-debug-004',
    ],
    
    artifactIds: [
      'artifact-loan-fix',
    ],
    
    contextAutomationId: 'loan-approval-automation',
    
    userId: 'user-james',
    userName: 'James Patterson',
    userEmail: 'james.patterson@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-10-16T08:00:00.000Z',
    lastMessageDate: '2025-10-16T09:15:00.000Z',
    lastUpdatedDate: '2025-10-16T09:15:00.000Z',
    
    messageCount: 4,
    artifactCount: 1,
    totalTokens: 3120,
    
    tags: [
      { id: 'tag-debug', label: 'Debugging', color: 'red' },
      { id: 'tag-bug-fix', label: 'Bug Fix', color: 'orange' },
    ],
    
    isFavorite: false,
    isPinned: true,
    
    isShared: false,
  },
  
  {
    id: 'conv-learn-decision-models',
    title: 'Learn About Decision Models',
    description: 'Training session on creating effective decision models',
    
    type: 'training',
    status: 'archived',
    
    messageIds: [
      'msg-learn-001',
      'msg-learn-002',
      'msg-learn-003',
      'msg-learn-004',
      'msg-learn-005',
    ],
    
    artifactIds: [
      'artifact-dm-guide',
      'artifact-dm-examples',
    ],
    
    userId: 'user-new',
    userName: 'Alex Johnson',
    userEmail: 'alex.johnson@company.com',
    aiModel: 'gpt-4',
    aiVersion: '2024-05-13',
    
    createdDate: '2025-09-20T10:00:00.000Z',
    lastMessageDate: '2025-09-20T11:30:00.000Z',
    lastUpdatedDate: '2025-09-20T11:30:00.000Z',
    
    messageCount: 5,
    artifactCount: 2,
    totalTokens: 4560,
    
    tags: [
      { id: 'tag-training', label: 'Training', color: 'green' },
      { id: 'tag-education', label: 'Education', color: 'blue' },
    ],
    
    isFavorite: false,
    isPinned: false,
    
    isShared: false,
  },
];
